import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'
import Nav from '@/components/Nav'
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* className={inter.className} */}
        <div className='w-full bg-[#131313] fixed left-0 z-50'>      <Nav/></div>

        {children}
        <Footer/>
      </body>

      
    </html>
  )
}
