import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'
import Nav from '@/components/Nav'
// const inter = Inter({ subsets: ['latin'] })
import localFont from "next/font/local";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Helvetica = localFont({
  src: "/fonts/Helvetica.ttf",
  variable: "--font-helvetica-sans",
  weight: "100 900",
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${Helvetica.variable} antialiased`}>
      {/* className={inter.className} */}
        <div className='w-full bg-[#131313] fixed left-0 z-50'>      <Nav/></div>

        {children}
        <Footer/>
      </body>

      
    </html>
  )
}
